assets_dir: ./assets

nodes:
  node01:
    address: 192.168.33.111
    labels:
    - "node-role.kubernetes.io/master"
    taints:
    - "node-role.kubernetes.io/master=:NoSchedule"
  node02:
    address: 192.168.33.112
    labels:
    - "node-role.kubernetes.io/master"
    taints:
    - "node-role.kubernetes.io/master=:NoSchedule"
  node03:
    address: 192.168.33.113
  node04:
    address: 192.168.33.114

kubernetes:
  networking:
    service_subnet: '10.254.0.0/24'
    pod_subnet: '10.244.0.0/16'
    dns_domain: 'cluster.local'
