nodes:
  node01:
    hostname: 192.168.33.111
    labels:
      "k8s.unstable.cloud/master":
      "etcd.unstable.cloud/member": node01
    taints:
      "node-role.kubernetes.io/master": :NoSchedule"
      "etcd.unstable.cloud/member": node02
  node02:
    hostname: 192.168.33.112
    labels:
      "k8s.unstable.cloud/master":
      "etcd.unstable.cloud/member": node03
    taints:
      "node-role.kubernetes.io/master": :NoSchedule"
  node03:
    hostname: 192.168.33.113
  node04:
    hostname: 192.168.33.114

bootstrap: {}

kubernetes:
  control_plane_endpoint: '192.168.33.101:6443'
