nodes:
  172.18.13.111:
    labels:
      "node-role.kubernetes.io/master":
      "etcd.unstable.cloud/member": node01
    taints:
      "node-role.kubernetes.io/master": :NoSchedule"
  172.18.13.112:
    labels:
      "node-role.kubernetes.io/master":
      "etcd.unstable.cloud/member": node02
    taints:
      "node-role.kubernetes.io/master": :NoSchedule"
  172.18.13.113:
    labels:
      "node-role.kubernetes.io/master":
      "etcd.unstable.cloud/member": node03
    taints:
      "node-role.kubernetes.io/master": :NoSchedule"
  172.18.13.121:
  172.18.13.122:
  172.18.13.123:

bootstrap:
  node:
    hostname: 172.18.13.111

metallb:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.18.13.140-172.18.13.200

kubernetes:
  control_plane_endpoint: '172.18.13.101:6443'
