nodes:
  172.18.13.111:
    labels:
      "k8s.unstable.cloud/master":
      "etcd.unstable.cloud/member": node01
    taints:
      "node-role.kubernetes.io/master": ":NoSchedule"
  172.18.13.112:
    labels:
      "k8s.unstable.cloud/master":
      "etcd.unstable.cloud/member": node02
    taints:
      "node-role.kubernetes.io/master": ":NoSchedule"
  172.18.13.113:
    labels:
      "k8s.unstable.cloud/master":
      "etcd.unstable.cloud/member": node03
    taints:
      "node-role.kubernetes.io/master": ":NoSchedule"
  172.18.13.121:
  172.18.13.122:
  172.18.13.123:

bootstrap:
  node:
    hostname: 172.18.13.121

lb:
  metallb:
    config: |
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 172.18.13.101/32
        - 172.18.13.140-172.18.13.200

cni:
  flannel:
    backend: host-gw

kubernetes:
  kubernetes_version: v1.15.11
  cluster_name: unstable
  control_plane_endpoint: '172.18.13.101:6443'

  proxy:
    config:
      mode: 'ipvs'
