namespace: kube-system

resources:
- https://github.com/kubernetes-sigs/kube-storage-version-migrator/manifests/?ref=acdee30ced218b79e39c6a701985e8cd8bd33824

images:
- name: REGISTRY/storage-version-migration-initializer:VERSION
  newName: asia.gcr.io/k8s-artifacts-prod/storage-migrator/storage-version-migration-initializer
  newTag: v0.0.3
- name: REGISTRY/storage-version-migration-migrator:VERSION
  newName: asia.gcr.io/k8s-artifacts-prod/storage-migrator/storage-version-migration-migrator
  newTag: v0.0.3
- name: REGISTRY/storage-version-migration-trigger:VERSION
  newName: asia.gcr.io/k8s-artifacts-prod/storage-migrator/storage-version-migration-trigger
  newTag: v0.0.3
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: migrator
    namespace: kube-system
  patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/livenessProbe
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: --kubeconfig=/etc/migrator/kubeconfig
- target:
    group: apps
    version: v1
    kind: Deployment
    name: trigger
    namespace: kube-system
  patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/livenessProbe
    - op: add
      path: /spec/template/spec/containers/0/args
      value: ["--kubeconfig=/etc/migrator/kubeconfig"]
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: migrator
    namespace: NAMESPACE
  spec:
    template:
      spec:
        containers:
        - name: migrator
          volumeMounts:
          - mountPath: /etc/migrator
            name: kubeconfig
        volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig-in-cluster-latest
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: trigger
    namespace: NAMESPACE
  spec:
    template:
      spec:
        containers:
        - name: trigger
          volumeMounts:
          - mountPath: /etc/migrator
            name: kubeconfig
        volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig-in-cluster-latest
